#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
git lfs post-commit "$@"
REPO_ROOT="$(git rev-parse --show-toplevel)"
DEMO_REPO="git@github.com:chrisquices/strata-ui-demo.git"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
if [ ! -d "$REPO_ROOT/dist" ]; then exit 0; fi
git clone "$DEMO_REPO" "$TMP"
rm -rf "$TMP"/*
cp -r "$REPO_ROOT/dist/." "$TMP"/
cd "$TMP"
git config user.name "Christopher Quiñonez"
git config user.email "rosphrethric@gmail.com"
git add -A
git diff --staged --quiet && exit 0
git commit -m "deploy"
git push
